apiVersion: v1
kind: Pod
metadata:
  name: do-app2
spec:
      containers:
      - name: do-app2
        image: alpine
        volumeMounts:
          - name: my-data
            mountPath: /var/dodisk
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/dodisk/do-app2.txt; sleep 20; echo do-app2>> /var/dodisk/do-app2.txt; done"]
        ports:
        - containerPort: 7171
          protocol: TCP
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: do-disk-8g