apiVersion: v1
kind: Pod
metadata:
  name: do-app
spec:
      containers:
      - name: do-app
        image: alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: my-data
            mountPath: /var/dodisk
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/dodisk/do-app.txt; sleep 20; echo do-app >> /var/dodisk/do-app.txt; done"]
        ports:
        - containerPort: 7171
          protocol: TCP
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: do-disk-2g